# Claves de tu proyecto en SonarCloud (Actualizadas al Lab 06)
sonar.projectKey=Lab6_Intelligent_Search
sonar.organization=santiagoacostazamora
sonar.host.url=https://sonarcloud.io
sonar-scanner
# Nombre y versión
sonar.projectName=Ucv-ate-si-lab-06
sonar.projectVersion=1.0

# Directorio de tu código fuente (Apuntamos a src para que no escanee archivos innecesarios)
sonar.sources=src

# Exclusiones de seguridad (¡La línea mágica sigue siendo útil!)
sonar.exclusions=**/.venv/**,**/__pycache__/**